/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#57676a",
        "inverse-on-surface": "#eef1f7",
        "secondary": "#516164",
        "surface": "#f7f9ff",
        "error": "#ba1a1a",
        "tertiary-container": "#005048",
        "on-error-container": "#93000a",
        "surface-container": "#ebeef4",
        "primary-fixed-dim": "#95cfe7",
        "surface-container-high": "#e5e8ee",
        "secondary-fixed-dim": "#b9cacd",
        "on-primary-fixed": "#001f29",
        "secondary-fixed": "#d4e6e9",
        "primary-container": "#004d61",
        "primary": "#003544",
        "surface-variant": "#dfe3e8",
        "tertiary-fixed": "#9ff2e4",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#00201c",
        "outline": "#70787c",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "on-tertiary-container": "#72c3b7",
        "surface-container-highest": "#dfe3e8",
        "on-surface": "#181c20",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f1f4fa",
        "on-primary-container": "#83bdd4",
        "on-surface-variant": "#40484c",
        "on-primary-fixed-variant": "#014d61",
        "tertiary-fixed-dim": "#84d5c8",
        "inverse-primary": "#95cfe7",
        "error-container": "#ffdad6",
        "primary-fixed": "#b9eaff",
        "on-tertiary-fixed-variant": "#005048",
        "surface-dim": "#d7dae0",
        "on-secondary-fixed": "#0e1e21",
        "outline-variant": "#c0c8cc",
        "surface-bright": "#f7f9ff",
        "tertiary": "#003731",
        "on-secondary-fixed-variant": "#3a494c",
        "secondary-container": "#d4e6e9",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#28657a",
        "inverse-surface": "#2d3135",
        "on-background": "#181c20",
        "background": "#f7f9ff"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}
